version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql #/var/lib/mysql is on the container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports: 
      - '8000:80'
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306 # DB is the service declared above
      WORDPRESS_DB_USER: wordpress # Should match MYSQL_USER
      WORDPRESS_DB_PASSWORD: wordpress # Should matchh MYSQL_PASSWORD
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
